spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/monitor}
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

logging:
  level:
    com.monitor: WARN
